CREATE DATABASE Medium
GO

USE Medium
GO

CREATE TABLE dbo.Posts 
(
	Slug		NVARCHAR(250) NOT NULL PRIMARY KEY,
	Title		NVARCHAR(200) NOT NULL,
	Body		NVARCHAR(MAX) NOT NULL,
	Published   BIT			  NOT NULL,
	PublishedAt DATETIME	  NOT NULL,
)
GO

CREATE TABLE dbo.Tags 
(
	Name NVARCHAR(250) NOT NULL PRIMARY KEY
)
GO

CREATE TABLE dbo.PostTagJunction 
(
	PostSlug NVARCHAR(250),
	TagName  NVARCHAR(250)

	CONSTRAINT Pk	   PRIMARY KEY (PostSlug, TagName),
	CONSTRAINT Fk_Post FOREIGN KEY (PostSlug) REFERENCES Posts (Slug),
	CONSTRAINT Fk_Tag  FOREIGN KEY (TagName)  REFERENCES Tags (Name)
)
GO